### ISSUE TITLE
[BUG] Left and right quote cause strange behaviour

### ISSUE THREAD

**Issue by Luhav** [n-ivkovic/tspreed#13] opened 2021-10-14 16:39 UTC
## Issue:
Left and Right Double Quotation Marks (U+201C and U+201D, respectively), seem to cause weird unexpected behaviour. The quotes themselves do not show at all, and the last two letters of the word following the Left Double Quotation Mark also seem to not show. This has been tested with multiple passages.
### Example:
![new tspreed bug](https://user-images.githubusercontent.com/43188089/137357295-c1639cb5-0fe4-4ef5-9864-e81601f2b078.gif)
The passage used here:
> We get vanilla from the pods that grow on the vanilla orchid; in fact, the word vanilla means “little pod” in Spanish.

## Steps for reproduction:
- have a text file which contains Left and Right Double Quotation Marks hugging a section of the text
- read with Tspreed

## Expected behaviour:
The quotes should be rendered, and the last two letters shouldn't be hacked off the first word in the quote.

**Comment by n-ivkovic** [comment] 2021-10-18 12:04
Looking into this, it seems the issue is that the -c option of GNU cut(1) does not support multi-byte characters, such as the double quotation marks, unlike other cut implementations. I'm assuming you're using GNU coreutils as the machine name in the example gif indicates you're running Arch Linux.

The solution to this issue is to utilise awk(1) instead of cut(1) where required. However, some quick benchmarking indicates the required functionality runs 4-5x slower when performed via awk compared to cut. To mitigate this performance hit where possible, the script will ensure that cut is used when the available cut implementation correctly handles multi-byte characters.

I will close this issue once this change is committed to develop.

**Comment by n-ivkovic** [comment] 2021-10-22 23:03
This issue has now been fixed in 397d40e

**Closed as completed by n-ivkovic** 2021-10-22 23:03 UTC
